
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Clear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - run: ssh -i private_key -o StrictHostKeyChecking=accept-new deployer@${{ secrets.SSH_HOST }}
      - run: ssh -i private_key deployer@${{ secrets.SSH_HOST }} 'rm -r ${{ secrets.DEPLOY_PATH }}/*'
  Prepare:
    runs-on: ubuntu-latest
    needs: [Clear]
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - run: ssh -i private_key -o StrictHostKeyChecking=accept-new deployer@${{ secrets.SSH_HOST }}
      - name: Pull latest changes
        run: ssh -i private_key deployer@${{ secrets.SSH_HOST }} 'cd ${{ secrets.DEPLOY_TEMP }}; git pull;'
      - name: Unzip build package
        run: ssh -i private_key deployer@${{ secrets.SSH_HOST }} 'cd ${{ secrets.DEPLOY_TEMP }}; unzip web.zip'
  Deploy:
    runs-on: ubuntu-latest
    needs: [Prepare]
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - run: ssh -i private_key -o StrictHostKeyChecking=accept-new deployer@${{ secrets.SSH_HOST }}
      - name: Deploy web package
        run: ssh -i private_key deployer@${{ secrets.SSH_HOST }} 'cd ${{ secrets.DEPLOY_TEMP }}; cp -r web/* ${{ secrets.DEPLOY_PATH }}'
